(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={data:null,index:0,geo:null,model:null,layers:{physical:true,means:true,chemistry:true,model:true},theme:matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'};
const colors=['#82e6d2','#e8bd7a','#85bfe6','#f29b72','#c6a5e6'];
const fmt=(v,d=3)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const intervalLabel=r=>`${fmt(r.depth_top_cm,1)}–${fmt(r.depth_bottom_cm,1)} cm`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function setTheme(t){state.theme=t;document.documentElement.dataset.theme=t;$('#themeButton').innerHTML=t==='dark'?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/></svg>';drawChart()}
function buildRail(){const rail=$('#depthRail');rail.innerHTML='';CoreData.SEGMENTS.forEach(s=>{const el=document.createElement('div');el.className='segment-block';el.dataset.segment=s.id;el.style.top=`${s.top/CoreData.DEPTH_MAX*100}%`;el.style.height=`${(s.bottom-s.top)/CoreData.DEPTH_MAX*100}%`;el.innerHTML=`<button type="button">${s.id}</button><small>${s.top}</small>`;el.querySelector('button').addEventListener('click',()=>selectDepth(s.top+.01));rail.append(el)});const end=document.createElement('small');end.textContent='163';end.style.cssText='position:absolute;bottom:-.5rem;right:0;color:var(--faint);font-size:var(--text-xs)';rail.append(end)}
function buildSegments(){const grid=$('#segmentGrid');grid.innerHTML='';CoreData.SEGMENTS.forEach(s=>{const b=document.createElement('button');b.textContent=s.id;b.title=`${s.top}–${s.bottom} cm`;b.addEventListener('click',()=>selectDepth(s.top+.01));grid.append(b)})}
function fillSelect(el,items,empty){el.innerHTML='';if(!items.length){el.add(new Option(empty,''));el.disabled=true;return}el.disabled=false;items.forEach(x=>el.add(new Option(x,x)))}
function loadVideo(segment){const video=$('#coreVideo'),src=encodeURI(`./${segment.video}`);if(video.dataset.segment===segment.id)return;video.pause();video.classList.remove('ready');video.dataset.segment=segment.id;video.src=src;video.load();$('#videoSegment').textContent=segment.id;$('#videoRange').textContent=`${segment.top}–${segment.bottom} cm`;$('#videoPlaceholder').classList.remove('hidden');$('#videoPlaceholder p').textContent='Loading CT segment…';$('.video-shell').classList.remove('playing')}
function selectDepth(depth){const i=state.data.aligned.findIndex(r=>depth>=r.depth_top_cm&&depth<r.depth_bottom_cm);selectIndex(i>=0?i:state.data.aligned.length-1)}
function selectIndex(i){if(!state.data)return;state.index=Math.max(0,Math.min(i,state.data.aligned.length-1));const r=state.data.aligned[state.index],seg=CoreData.segmentAt(r.depth_mid_cm);$('#sampleSelect').value=String(state.index);$('#depthSlider').value=String(state.index);$('#depthSlider').style.setProperty('--fill',`${state.index/Math.max(1,state.data.aligned.length-1)*100}%`);$('#sampleRange').textContent=intervalLabel(r);$('#sampleSegment').textContent=seg.id;$('#factBrine').innerHTML=valueWithSD(r.brine_mean,r.brine_sd);$('#factPorosity').innerHTML=valueWithSD(r.porosity_mean,r.porosity_sd);$('#factDensity').innerHTML=valueWithSD(r.density_mean,r.density_sd);$('#factCoverage').textContent=r.coverage_fraction===null?'—':`${fmt(r.coverage_fraction*100,0)}%`;updateVariableFacts(r);$('#railSelection').style.top=`${r.depth_top_cm/CoreData.DEPTH_MAX*100}%`;$('#railSelection').style.height=`${(r.depth_bottom_cm-r.depth_top_cm)/CoreData.DEPTH_MAX*100}%`;$$('.segment-block,.segment-grid button').forEach(el=>el.classList.toggle('active',(el.dataset.segment||el.textContent.trim())===seg.id));loadVideo(seg);drawChart();$('#sampleSummary').animate([{opacity:.35,transform:'translateY(4px)'},{opacity:1,transform:'none'}],{duration:360,easing:'cubic-bezier(.16,1,.3,1)'})}
function valueWithSD(v,sd){return v===null?'—':`${fmt(v)}${sd===null?'':` <small>± ${fmt(sd)}</small>`}`}
function updateVariableFacts(r){const gv=state.geo?CoreData.num(r._chem[state.geo]):null,mv=state.model?CoreData.num(r._model[state.model]):null;$('#factGeoLabel').textContent=state.geo||'Geochemistry';$('#factGeo').textContent=fmt(gv);$('#factModelLabel').textContent=state.model||'Model';$('#factModel').textContent=fmt(mv)}
function initData(d){state.data=d;state.geo=d.chemVariables[0]||null;state.model=d.modelVariables[0]||null;fillSelect($('#geoSelect'),d.chemVariables,'No numeric chemistry columns');fillSelect($('#modelSelect'),d.modelVariables,'No numeric model columns');$('#geoSelect').value=state.geo||'';$('#modelSelect').value=state.model||'';$('#sampleSelect').innerHTML='';d.aligned.forEach((r,i)=>$('#sampleSelect').add(new Option(`${intervalLabel(r)} · ${r.segment}`,String(i))));$('#depthSlider').max=String(Math.max(0,d.aligned.length-1));$('#sampleCount').textContent=`${d.aligned.length} samples`;
 const hasPhysical=d.physical.rows.length>0,hasChem=d.chem.some(r=>Object.keys(r).some(k=>!k.startsWith('_')&&CoreData.num(r[k])!==null)),hasModels=d.models.length>0,ready=hasPhysical&&hasChem;const status=$('#dataStatus');status.className=`data-status ${ready?'ready':'error'}`;status.innerHTML=`<i></i>${ready?'Repository data aligned':'Partial data loaded'}`;const coverage=d.aligned.filter(r=>r.coverage_fraction>0).length;$('#qualityText').textContent=`${d.physical.rows.length} physical layers · ${d.aligned.length} chemical intervals · ${coverage} intervals with physical coverage${hasModels?` · ${d.models.length} model rows`:''}.`;
 if(d.errors.length)toast('Some repository files were not available. The interface remains operational.');selectIndex(0)}
function drawChart(){const svg=$('#profileChart');if(!svg||!state.data||$('#profileDock').hidden)return;const w=Math.max(780,svg.clientWidth||1000),h=Math.max(380,svg.clientHeight||560),m={t:42,r:20,b:24,l:54},tracks=[{key:'brine',label:'Brine',raw:r=>r.brine,mean:r=>r.brine_mean,color:colors[0]},{key:'porosity',label:'Porosity',raw:r=>r.porosity,mean:r=>r.porosity_mean,color:colors[1]},{key:'density',label:'Density',raw:r=>r.density,mean:r=>r.density_mean,color:colors[2]}];if(state.geo)tracks.push({key:'geo',label:state.geo,chem:r=>CoreData.num(r._chem[state.geo]),color:colors[3]});if(state.model)tracks.push({key:'model',label:state.model,chem:r=>CoreData.num(r._model[state.model]),color:colors[4]});const gap=24,tw=(w-m.l-m.r-gap*(tracks.length-1))/tracks.length,y=d=>m.t+d/CoreData.DEPTH_MAX*(h-m.t-m.b);let out='';for(let d=0;d<=160;d+=20)out+=`<line class="chart-grid" x1="${m.l}" x2="${w-m.r}" y1="${y(d)}" y2="${y(d)}"/><text class="chart-axis" x="${m.l-10}" y="${y(d)+4}" text-anchor="end">${d}</text>`;out+=`<text class="chart-axis" transform="translate(14 ${m.t+(h-m.t-m.b)/2}) rotate(-90)" text-anchor="middle">Depth (cm)</text>`;tracks.forEach((t,j)=>{const x0=m.l+j*(tw+gap),raw=t.raw?state.data.physical.rows.map(r=>({x:t.raw(r),d:r._mid})).filter(p=>p.x!==null):state.data.aligned.map(r=>({x:t.chem(r),d:r.depth_mid_cm})).filter(p=>p.x!==null),vals=raw.map(p=>p.x),means=t.mean?state.data.aligned.map(r=>({x:t.mean(r),d:r.depth_mid_cm})).filter(p=>p.x!==null):[];if(!vals.length&&!means.length){out+=`<text class="chart-title" x="${x0}" y="20">${escapeHtml(t.label)}</text><text class="chart-axis" x="${x0}" y="40">No data</text>`;return}const all=[...vals,...means.map(p=>p.x)],lo=Math.min(...all),hi=Math.max(...all),span=hi-lo||1,x=v=>x0+(v-lo)/span*tw;out+=`<text class="chart-title" x="${x0}" y="20">${escapeHtml(t.label)}</text><text class="chart-axis" x="${x0}" y="36">${fmt(lo,2)}</text><text class="chart-axis" x="${x0+tw}" y="36" text-anchor="end">${fmt(hi,2)}</text>`;if(raw.length>1&&((t.raw&&state.layers.physical)||(!t.raw&&((t.key==='geo'&&state.layers.chemistry)||(t.key==='model'&&state.layers.model)))))out+=`<path class="chart-line" stroke="${t.color}" d="${raw.map((p,k)=>`${k?'L':'M'}${x(p.x).toFixed(1)},${y(p.d).toFixed(1)}`).join(' ')}"/>`;if(t.mean&&state.layers.means)means.forEach(p=>out+=`<circle class="chart-means" stroke="${t.color}" cx="${x(p.x)}" cy="${y(p.d)}" r="3.4"/>`) });const r=state.data.aligned[state.index];out+=`<rect class="chart-sample" x="${m.l}" width="${w-m.l-m.r}" y="${y(r.depth_top_cm)}" height="${Math.max(2,y(r.depth_bottom_cm)-y(r.depth_top_cm))}"/>`;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=out;svg.onclick=e=>{const rect=svg.getBoundingClientRect(),py=(e.clientY-rect.top)/rect.height*h,d=(py-m.t)/(h-m.t-m.b)*CoreData.DEPTH_MAX;if(d>=0&&d<=CoreData.DEPTH_MAX)selectDepth(d)};buildLegend(tracks)}
function buildLegend(tracks){$('#chartLegend').innerHTML=tracks.map(t=>`<span><i style="--legend-color:${t.color}"></i>${escapeHtml(t.label)}</span>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initCanvas(){const c=$('#iceField'),ctx=c.getContext('2d'),particles=Array.from({length:90},()=>({x:Math.random(),y:Math.random(),r:.5+Math.random()*2,v:.00005+Math.random()*.00012,a:.08+Math.random()*.28}));function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio}addEventListener('resize',resize);resize();function frame(){ctx.clearRect(0,0,c.width,c.height);const dark=state.theme==='dark';ctx.fillStyle=dark?'#061011':'#eaf2ef';ctx.fillRect(0,0,c.width,c.height);const g=ctx.createRadialGradient(c.width*.52,c.height*.48,0,c.width*.52,c.height*.48,Math.max(c.width,c.height)*.58);g.addColorStop(0,dark?'rgba(44,120,111,.16)':'rgba(42,130,115,.16)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);particles.forEach(p=>{p.y-=p.v;if(p.y<-.02)p.y=1.02;ctx.beginPath();ctx.arc(p.x*c.width,p.y*c.height,p.r*devicePixelRatio,0,Math.PI*2);ctx.fillStyle=dark?`rgba(151,230,216,${p.a})`:`rgba(15,90,78,${p.a*.7})`;ctx.fill()});requestAnimationFrame(frame)}frame()}
function bind(){setTheme(state.theme);$('#themeButton').onclick=()=>setTheme(state.theme==='dark'?'light':'dark');$('#sampleSelect').onchange=e=>selectIndex(Number(e.target.value));$('#depthSlider').oninput=e=>selectIndex(Number(e.target.value));$('#geoSelect').onchange=e=>{state.geo=e.target.value||null;selectIndex(state.index)};$('#modelSelect').onchange=e=>{state.model=e.target.value||null;selectIndex(state.index)};$$('.switch').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;state.layers[k]=!state.layers[k];b.setAttribute('aria-checked',String(state.layers[k]));drawChart()});$$('.mode-switch button').forEach(b=>b.onclick=()=>{$$('.mode-switch button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.body.classList.toggle('ct-focus',b.dataset.view==='ct')});$('#coreVideo').addEventListener('loadeddata',()=>{$('#videoPlaceholder').classList.add('hidden')});$('#coreVideo').addEventListener('error',()=>{$('#videoPlaceholder').classList.remove('hidden');$('#videoPlaceholder p').textContent='CT video unavailable in this deployment';$('.video-shell').classList.remove('playing')});$('#coreVideo').addEventListener('play',()=>$('.video-shell').classList.add('playing'));$('#coreVideo').addEventListener('pause',()=>$('.video-shell').classList.remove('playing'));$('#playControl').onclick=()=>toggleVideo();$('#openProfile').onclick=()=>{$('#profileDock').hidden=false;requestAnimationFrame(drawChart)};$('#closeProfile').onclick=()=>$('#profileDock').hidden=true;$('#resetZoom').onclick=()=>{selectIndex(0);toast('Depth selection reset')};$('#exportData').onclick=exportAligned;$('#presentButton').onclick=()=>document.body.classList.toggle('presenting');$('#fullscreenButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('#helpButton').onclick=()=>$('#helpModal').showModal();$('#consoleToggle').onclick=()=>document.body.classList.toggle('console-hidden');addEventListener('resize',drawChart);addEventListener('keydown',e=>{if(e.target.matches('input,select,button'))return;if(e.key==='ArrowRight')selectIndex(state.index+1);if(e.key==='ArrowLeft')selectIndex(state.index-1);if(e.key===' '){e.preventDefault();toggleVideo()}if(e.key.toLowerCase()==='h')document.body.classList.toggle('presenting');if(e.key.toLowerCase()==='f')$('#fullscreenButton').click();if(e.key==='?')$('#helpModal').showModal()})}
function toggleVideo(){const v=$('#coreVideo');if(v.paused)v.play().catch(()=>toast('Select play in the video viewer'));else v.pause()}
function exportAligned(){if(!state.data)return;const blob=new Blob([CoreData.toCSV(state.data.aligned)],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='core16_aligned_profile.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Aligned CSV exported')}
buildRail();buildSegments();bind();initCanvas();CoreData.load().then(initData).catch(e=>{console.error(e);$('#dataStatus').className='data-status error';$('#dataStatus').innerHTML='<i></i>Data could not be loaded';$('#qualityText').textContent='Place the three CSV files beside index.html, then reload the page.';toast('Repository data could not be loaded')});
})();
